# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
pool:
  vmImage: windows-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.0'
  displayName: 'Install Node.js'
- script:
    npm install
  displayName: 'npm install'
- script:
      npm run apitest
  displayName: 'API script execution'
  condition: always()
- script:
      npm run webtest
  displayName: 'Web script execution'
  condition: always()
- script:
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './reports/apiAutomation/junit-results/apiTestSummaryResults.xml'
    testRunTitle: 'API Execution Results'
    mergeTestResults: false
  condition: always()
- script:
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './reports/webAutomation/junit-results/webTestSummaryResults.xml'
    testRunTitle: 'Web Execution Results'
    mergeTestResults: false
  condition: always()
- task: CopyFiles@2
  inputs:
    SourceFolder: './reports/apiAutomation/azure'
    Contents: '**'
    TargetFolder: '$(Build.BuildNumber)'
  condition: always() 
- task: CopyFiles@2
  inputs:
    SourceFolder: './reports/webAutomation/azure'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: always() 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BuildNumber)'
    ArtifactName: 'API Execution Results'
    publishLocation: 'Container'
  condition: always()
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'UI Execution Results'
    publishLocation: 'Container'
  condition: always()